export const postgresDdl = `
CREATE SCHEMA catalog;
CREATE TYPE catalog.status AS ENUM ('draft', 'active');
CREATE TABLE catalog.products (
  tenant_id uuid NOT NULL,
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name character varying(255) NOT NULL DEFAULT 'unnamed, item; ok',
  price numeric(12, 2) DEFAULT 0 CHECK (price >= 0),
  state catalog.status DEFAULT 'draft'::catalog.status,
  created_at timestamp with time zone DEFAULT now(),
  attributes jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT products_pkey PRIMARY KEY (tenant_id, id),
  CONSTRAINT products_name UNIQUE (tenant_id, name)
);
CREATE TABLE catalog.variants (
  id bigserial PRIMARY KEY,
  tenant_id uuid NOT NULL,
  product_id bigint NOT NULL,
  sku varchar(100) NOT NULL,
  CONSTRAINT variant_sku UNIQUE (tenant_id, sku)
);
ALTER TABLE ONLY catalog.variants ADD CONSTRAINT variant_product
  FOREIGN KEY (tenant_id, product_id) REFERENCES catalog.products (tenant_id, id)
  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX variant_lookup ON catalog.variants USING btree (product_id DESC);
COMMENT ON TABLE catalog.products IS 'Catalog products';
COMMENT ON COLUMN catalog.products.name IS 'Display name';
`;

export const mysqlDdl = `
CREATE TABLE \`shop\`.\`products\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`name\` varchar(200) NOT NULL DEFAULT 'new, product; name' COMMENT 'Display name',
  \`enabled\` tinyint(1) NOT NULL DEFAULT 1,
  \`status\` enum('draft','active') DEFAULT 'draft',
  \`price\` decimal(10,2) DEFAULT 0,
  \`modified\` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`product_name\` (\`name\`),
  KEY \`price_idx\` (\`price\` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Products';
CREATE TABLE \`shop\`.\`variants\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`product_id\` bigint unsigned,
  \`sku\` varchar(40) NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`variant_product\` FOREIGN KEY (\`product_id\`) REFERENCES \`shop\`.\`products\` (\`id\`) ON DELETE SET NULL
);
`;
