import { expect, test } from './test';
import { postgresDdl, mysqlDdl } from '$/sql/fixtures';

for (const [database, source] of [
  ['postgresql', postgresDdl],
  ['mysql', mysqlDdl]
] as const) {
  test(`imports ${database} SQL and exports current schema in both dialects`, async ({ page }) => {
    await page.goto('/edit');
    await page.getByRole('button', { name: 'Import SQL', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByLabel('Source database').selectOption(database);
    if (database === 'mysql')
      await dialog.getByLabel('SQL file', { exact: true }).setInputFiles({
        name: 'shop.sql',
        mimeType: 'application/sql',
        buffer: Buffer.from(source)
      });
    else await dialog.getByLabel('SQL DDL').fill(source);
    await dialog.getByRole('button', { name: 'Preview schema', exact: true }).click();
    await expect(dialog.getByRole('region', { name: 'SQL import preview' })).toContainText(
      '2 tables'
    );
    await expect(dialog.getByRole('region', { name: 'SQL import preview' })).toContainText(
      '1 foreign keys'
    );
    await dialog.getByRole('button', { name: 'Replace with ER diagram', exact: true }).click();
    const svg = page.locator('#container svg.erDiagram');
    await expect(svg).toContainText('products');
    await expect(svg).toContainText('variants');
    await page.keyboard.press('Control+k');
    await page.getByLabel('Search diagram or command').fill('Export diagram');
    await page.getByRole('button', { name: 'Export diagram', exact: true }).click();
    await dialog
      .locator('label')
      .filter({ has: page.locator('input[value="sql"]') })
      .click();
    await expect(dialog.getByLabel('Target database')).toHaveValue(database);
    await expect(dialog.getByLabel('SQL preview')).toHaveValue(/CREATE TABLE/);
    await expect(dialog.getByLabel('SQL preview')).toHaveValue(/FOREIGN KEY/);
    await dialog.getByRole('button', { name: 'Copy SQL', exact: true }).click();
    await expect
      .poll(() => page.evaluate(() => navigator.clipboard.readText()))
      .toContain('FOREIGN KEY');
    const downloadEvent = page.waitForEvent('download');
    await dialog.getByRole('button', { name: 'Download SQL', exact: true }).click();
    const download = await downloadEvent;
    expect(download.suggestedFilename()).toMatch(/\.sql$/);
    await expect(dialog.getByLabel('SQL preview')).toHaveValue(
      database === 'postgresql' ? /GENERATED BY DEFAULT AS IDENTITY/ : /AUTO_INCREMENT/
    );
    await dialog
      .getByLabel('Target database')
      .selectOption(database === 'mysql' ? 'postgresql' : 'mysql');
    await expect(dialog.getByText(/Converted .* DDL to/)).toBeVisible();
    await expect(dialog.getByLabel('SQL preview')).toHaveValue(
      database === 'mysql' ? /GENERATED BY DEFAULT AS IDENTITY/ : /AUTO_INCREMENT/
    );
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.reload();
    await expect(svg).toContainText('products');
    expect(
      await page.evaluate(() => JSON.parse(localStorage.getItem('codeStore') ?? '{}').code)
    ).toContain('%% sql-schema-v1:');
  });
}

test('shows import errors and does not apply outdated previews', async ({ page }) => {
  await page.goto('/edit');
  await page.getByRole('button', { name: 'Import SQL', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('SQL DDL').fill('CREATE TABLE broken(id);');
  await dialog.getByRole('button', { name: 'Preview schema', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('Missing type');
  await expect(dialog.getByRole('button', { name: 'Replace with ER diagram' })).toBeDisabled();
  await dialog.getByLabel('SQL DDL').fill('CREATE TABLE users(id int PRIMARY KEY);');
  await dialog.getByRole('button', { name: 'Preview schema', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Replace with ER diagram' })).toBeEnabled();
  await dialog.getByLabel('SQL DDL').fill('CREATE TABLE changed(id int);');
  await expect(dialog.getByRole('button', { name: 'Replace with ER diagram' })).toBeDisabled();
});
